-- Reference schema matching the current project state.
create table if not exists public.menu_categories (
  id text primary key,
  name_ar text not null,
  icon text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  category_id text not null references public.menu_categories(id) on delete cascade,
  name_ar text not null,
  description_ar text,
  price numeric(10,2) not null check (price >= 0),
  badge_ar text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;

-- Public (anon) visitors only ever see active rows.
create policy "Public can read active menu categories"
on public.menu_categories for select
to anon
using (is_active = true);

create policy "Public can read active menu items"
on public.menu_items for select
to anon
using (is_active = true);

-- The signed-in admin must see ALL rows (including hidden ones) so the
-- admin panel can list and re-enable hidden products/categories. Without
-- this policy the admin list silently drops anything with is_active=false
-- and there is no way to un-hide it from the UI.
create policy "Admin can read all menu categories"
on public.menu_categories for select
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can read all menu items"
on public.menu_items for select
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

-- Writes are restricted to the single admin account server-side (RLS),
-- not just hidden client-side in admin.html — a signed-in user whose
-- email is not the admin's cannot write even if they call the API directly.
create policy "Admin can insert menu categories"
on public.menu_categories for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can update menu categories"
on public.menu_categories for update
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com')
with check ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can delete menu categories"
on public.menu_categories for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can insert menu items"
on public.menu_items for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can update menu items"
on public.menu_items for update
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com')
with check ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');

create policy "Admin can delete menu items"
on public.menu_items for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'i1yasser@hotmail.com');
